import React, { useEffect, useRef, useState } from 'react';
import ForceGraph2D from 'react-force-graph-2d';

const KnowledgeGraph: React.FC = () => {
  const [graphData, setGraphData] = useState({ nodes: [], links: [] });
  const [communityLabels, setCommunityLabels] = useState<Record<string, string>>({});
  const containerRef = useRef<HTMLDivElement>(null);
  const [dimensions, setDimensions] = useState({ width: 800, height: 600 });

  useEffect(() => {
    // Fetch the graph data generated by graphify (blog specific)
    Promise.all([
      fetch('/graphify-out/graph_blog.json').then(res => res.json()),
      fetch('/graphify-out/.graphify_labels_blog.json').then(res => res.json())
    ]).then(([data, labels]) => {
      setGraphData(data);
      setCommunityLabels(labels);
    }).catch(err => console.error('Error loading graph data:', err));

    // Handle resizing
    const updateDimensions = () => {
      if (containerRef.current) {
        setDimensions({
          width: containerRef.current.clientWidth,
          height: window.innerHeight - 250
        });
      }
    };

    window.addEventListener('resize', updateDimensions);
    updateDimensions();

    return () => window.removeEventListener('resize', updateDimensions);
  }, []);

  const getCommunityColor = (cid: number) => {
    const colors = [
      '#3b82f6', '#ef4444', '#10b981', '#f59e0b', '#8b5cf6', 
      '#ec4899', '#06b6d4', '#84cc16', '#6366f1', '#f43f5e'
    ];
    return colors[cid % colors.length];
  };

  return (
    <div ref={containerRef} className="w-full bg-gray-50 rounded-xl border border-gray-200 overflow-hidden relative" style={{ height: dimensions.height }}>
      <div className="absolute top-4 left-4 z-10 bg-white/80 backdrop-blur-sm p-4 rounded-lg border border-gray-200 shadow-sm max-w-xs">
        <h3 className="text-sm font-bold text-gray-900 mb-2">Knowledge Graph</h3>
        <p className="text-xs text-gray-500 mb-4">Interactive visualization of the research codebase and connections.</p>
        <div className="space-y-2">
          {Object.entries(communityLabels).slice(0, 6).map(([id, label]) => (
            <div key={id} className="flex items-center gap-2">
              <div className="w-2 h-2 rounded-full" style={{ backgroundColor: getCommunityColor(parseInt(id)) }}></div>
              <span className="text-[10px] font-medium text-gray-600 truncate">{label}</span>
            </div>
          ))}
          {Object.keys(communityLabels).length > 6 && (
            <p className="text-[10px] text-gray-400">+{Object.keys(communityLabels).length - 6} more communities</p>
          )}
        </div>
      </div>
      
      <ForceGraph2D
        graphData={graphData}
        width={dimensions.width}
        height={dimensions.height}
        nodeLabel="label"
        onNodeClick={(node: any) => {
          if (node.slug) {
            window.location.href = `/blog/${node.slug}`;
          }
        }}
        nodeColor={node => getCommunityColor((node as any).community)}
        nodeCanvasObject={(node, ctx, globalScale) => {
          const label = (node as any).label;
          const fontSize = 12 / globalScale;
          ctx.font = `${fontSize}px Inter, sans-serif`;
          const textWidth = ctx.measureText(label).width;
          const bckgDimensions = [textWidth, fontSize].map(n => n + fontSize * 0.2);

          ctx.fillStyle = 'rgba(255, 255, 255, 0.8)';
          ctx.fillRect((node as any).x - bckgDimensions[0] / 2, (node as any).y - bckgDimensions[1] / 2, bckgDimensions[0] as number, bckgDimensions[1] as number);

          ctx.textAlign = 'center';
          ctx.textBaseline = 'middle';
          ctx.fillStyle = getCommunityColor((node as any).community);
          ctx.fillText(label, (node as any).x, (node as any).y);

          (node as any).__bckgDimensions = bckgDimensions;
        }}
        nodePointerAreaPaint={(node, color, ctx) => {
          ctx.fillStyle = color;
          const bckgDimensions = (node as any).__bckgDimensions;
          bckgDimensions && ctx.fillRect((node as any).x - bckgDimensions[0] / 2, (node as any).y - bckgDimensions[1] / 2, bckgDimensions[0], bckgDimensions[1]);
        }}
        linkColor={() => '#e5e7eb'}
        linkDirectionalParticles={2}
        linkDirectionalParticleSpeed={0.005}
      />
    </div>
  );
};

export default KnowledgeGraph;
